language: java
jdk:
  - openjdk7
before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install coco-java
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
script:
 - ant build
 - ant test 
